-- counting the null values in the columns

SELECT 
COUNT_IF(ID IS NULL) AS ID_NULL,
COUNT_IF(MATCH_DATE IS NULL) AS MATCH_DATE_NULL,
COUNT_IF(MATCH_TIME IS NULL) AS MATCH_TIME_NULL,
COUNT_IF (COMPETITION IS NULL) AS COMPETITION_NULL,
COUNT_IF (ROUND IS NULL) AS ROUND_NULL,
COUNT_IF(MATCH_DAY IS NULL) AS MATCH_DAY_NULL,
COUNT_IF(VENUE IS NULL) AS VENUE_NULL,
COUNT_IF(RESULT IS NULL) AS RESULT_NULL,
COUNT_IF(GOALS_FOR IS NULL) AS GOALS_FOR_NULL,
COUNT_IF(GOALS_AGAINST IS NULL) AS GOALS_AGAINST_NULL,
COUNT_IF(OPPONENT IS NULL) AS OPPONENT_NULL,
COUNT_IF(EXPECTED_GOALS IS NULL) AS EXPECTED_GOALS_NULL, --- HAS NULL VALUE (2)
COUNT_IF(EXPECTED_GOALS_AGAINST IS NULL) AS EXPECTED_GOALS_AGAINST_NULL, --- HAS A NULL VALUE(2)
COUNT_IF(POSSESSION IS NULL) AS POSSESSION_NULL,
COUNT_IF(ATTENDANCE IS NULL) AS ATTENDANCE_NULL, -- HAS NULL VALUE (684)
COUNT_IF(CAPTAIN IS NULL) AS CAPTAIN_NULL,
COUNT_IF(FORMATION IS NULL) AS FORMATION_NULL,
COUNT_IF(OPPONENT_FORMATION IS NULL) AS OPPONENT_FORMATION_NULL,
COUNT_IF(REFEREE IS NULL) AS REFEREE_NULL,
COUNT_IF(MATCH_REPORT IS NULL) AS MATCH_REPORT_NULL,
COUNT_IF(NOTES IS NULL) AS NOTES_NULL,--- HAS NULL VALUE (3798)
COUNT_IF(SHOTS IS NULL) AS SHOTS_NULL,
COUNT_IF(SHOTS_ON_TARGET IS NULL) AS SHOTS_ON_TARGET_NULL,
COUNT_IF(AVG_SHOT_DISTANCE IS NULL) AS AVG_SHOT_DISTANCE_NULL, -- HAS NULL VALUE (4)
COUNT_IF(FREE_KICKS IS NULL) AS FREE_KICKS_NULL, --- HAS NULL VALUE (2)
COUNT_IF(PENALTIES_SCORED IS NULL) AS PENALTIES_SCORED_NULL,
COUNT_IF(PENALTIES_ATTEMPTED IS NULL) AS PENALTIES_ATTEMPTED_NULL,
COUNT_IF(SEASON IS NULL) AS SEASON_NULL,
COUNT_IF(TEAM IS NULL) AS TEAM_NULL

FROM SERIEA.VIEWS.TOTAL_RESULTS;


-- null values has been elimated and copied to a new materialized view 
CREATE OR REPLACE TABLE SERIEA.PUBLIC.PROCESS_TABLES AS
SELECT 
    COALESCE(EXPECTED_GOALS, 0) AS EXPECTED_GOALS,
    COALESCE(EXPECTED_GOALS_AGAINST, 0) AS EXPECTED_GOALS_AGAINST,
    COALESCE(ATTENDANCE, 0) AS ATTENDANCE,
    COALESCE(AVG_SHOT_DISTANCE, 0) AS AVG_SHOT_DISTANCE,
    COALESCE(FREE_KICKS, 0) AS FREE_KICKS,
    COALESCE(NOTES, 'NO NOTES') AS NOTES
FROM SERIEA.VIEWS.TOTAL_RESULTS;

-- data transformation  
SELECT * FROM SERIEA.VIEWS.TOTAL_RESULTS;

SELECT DISTINCT(FORMATION) FROM SERIEA.VIEWS.TOTAL_RESULTS
ORDER BY FORMATION;


SELECT FORMATION
FROM SERIEA.VIEWS.TOTAL_RESULTS
WHERE TRY_TO_DATE(FORMATION, 'DD-MM-YYYY') IS NOT NULL;


--
CREATE OR REPLACE TABLE SERIEA.PUBLIC.CLEANED_TABLE AS
SELECT *, 
CASE 
    WHEN FORMATION = '04-03-2003' THEN '4-3-3'
    WHEN FORMATION = '03-05-2002' THEN '3-5-2'
    WHEN FORMATION = '04-04-2002' THEN '4-2-2'
    WHEN FORMATION = '05-03-2002' THEN '5-3-2'
    WHEN FORMATION = '05-04-2001' THEN '5-4-1'
    WHEN FORMATION = '04-05-2001' THEN '4-5-1'
    ELSE FORMATION
    END AS FORMATION_CLEANED,
CASE 
    WHEN OPPONENT_FORMATION = '04-03-2003' THEN '4-3-3'
    WHEN OPPONENT_FORMATION = '03-05-2002' THEN '3-5-2'
    WHEN OPPONENT_FORMATION = '04-04-2002' THEN '4-2-2'
    WHEN OPPONENT_FORMATION = '05-03-2002' THEN '5-3-2'
    WHEN OPPONENT_FORMATION = '05-04-2001' THEN '5-4-1'
    WHEN OPPONENT_FORMATION = '04-05-2001' THEN '4-5-1'
    ELSE OPPONENT_FORMATION
END AS OPPONENT_FORMATION_CLEANED 
FROM SERIEA.VIEWS.TOTAL_RESULTS; 

-- creating a materialized view for the cleaned table
CREATE OR REPLACE MATERIALIZED VIEW  SERIEA.VIEWS.PROCESSED_VIEW AS 
SELECT * FROM SERIEA.PUBLIC.CLEANED_TABLE;


-- created table with home matches alone
CREATE OR REPLACE TABLE SERIEA.PUBLIC.home_matches
AS
SELECT * FROM SERIEA.VIEWS.TOTAL_RESULTS
WHERE VENUE = 'Home';

-- created a table with away matches alone

CREATE OR REPLACE TABLE SERIEA.PUBLIC.away_matches
AS
SELECT * FROM SERIEA.VIEWS.TOTAL_RESULTS
WHERE VENUE = 'Away';